{
 "title": "F1 ADX Statistics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Packets Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| union CarStatus, Lap, Participant, Session\n| where $__timeFilter(Timestamp)\n| count\n",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Driver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Participant\n| where $__timeFilter(Timestamp)\n| order by Timestamp \n| take 1\n| project Name",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Team",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Participant\n| where $__timeFilter(Timestamp)\n| order by Timestamp | take 1\n| extend DriverTeamId = TeamId\n| join  kind=rightsemi Teams  on $left.DriverTeamId == $right.Id\n| project Name\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Nationality",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Participant\n| where $__timeFilter(Timestamp)\n| order by Timestamp  | take 1\n| join  kind=rightsemi Nationalities  on $left.Nationality == $right.Id\n| project Name\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Current Lap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Lap\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp, SessionTime \n| take 1\n| project CurrentLapNum  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Car Position",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Lap\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp, SessionTime \n| take 1\n| project CarPosition   ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Current Lap Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Lap\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp, SessionTime \n| take 1\n| project CurrentLapTime  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Last Lap Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Lap\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp, SessionTime \n| take 1\n| project LastLapTime  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Best Lap Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Lap\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp, SessionTime \n| take 1\n| project BestLapTime  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Driver Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Lap\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp, SessionTime \n| take 1\n| project DriverStatus",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Lap Distance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Lap\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp, SessionTime \n| take 1\n| project LapDistance  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Distance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Lap\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp, SessionTime \n| take 1\n| project TotalDistance  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Time penalties",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Lap\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp, SessionTime \n| take 1\n| project TimePenalties   ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Pit Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Lap\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp, SessionTime \n| take 1\n| project PitStatus",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Grid Position",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Lap\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp, SessionTime \n| take 1\n| project GridPosition  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Result Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Lap\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp, SessionTime \n| take 1\n| project ResultStatus",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Laps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Session\n| where $__timeFilter(Timestamp)\n| order by Timestamp, SessionTime \n| take 1 \n| project TotalLaps ",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Session Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Session Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Session\n| where  $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 1 \n| project SessionTime",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Weather",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Session\n| where  $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 1 \n| project Weather  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Active Cars",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Participant\n| where  $__timeFilter(Timestamp)\n| order by Timestamp \n| take 1\n| project NumOfActiveCars ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Track",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Session\n| where  $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime  | take 1\n| join  kind=rightsemi Tracks on $left.TrackId == $right.Id\n| project Name",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Session Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Session\n| where  $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 1 \n| project SessionDuration  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "SessionTime Left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Session\n| where  $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 1 \n| project SessionTimeLeft ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Air Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Session\n| where  $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 10 \n| project AirTemp ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Track Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Session\n| where  $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 10 \n| project TrackTemp ",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Car", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where VehicleIndex == PlayerCarIndex and $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 1 \n| project Speed",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Engine",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 1 \n| project EngineRPM ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 100 \n| project Gear ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Anti lock brakes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 1 \n| project ABS  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Traction Control",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 1 \n| project TractionControl ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Fuel in Tank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 100\n| project FuelInTank",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Fuel Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 1 \n| project FuelCapacity",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Fuel Remaining Laps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 100 \n| project FuelRemainingLaps",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "DRS Allowed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 1\n| project DRSAllowed",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "FIA Flags",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 1 \n| project VehicleFIAFlags",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Damage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| take 1\n| project EngineDamage , GearBoxDamage ,FLWingDamage , FRWingDamage , RearWingDamage  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Gear & Clutch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project Gear , Timestamp\n",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project Clutch  , Timestamp\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Steering",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project Steering , Timestamp",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Throttle & Brake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project Timestamp, Throttle \n",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project Timestamp, Brake\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project Speed , Timestamp",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Engine Temperature",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project EngineTemp  , Timestamp\n",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Tires", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Compound",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| take 1\n| project TyreVisualCompound\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Wear",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 10, "x": 3, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| take 1\n| project FLTyreWear, FRTyreWear, RLTyreWear , RRTyreWear ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Damage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| take 1\n| project FLTyreDamage , FRTyreDamage , RLTyreDamage  , RRTyreDamage ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project FLTyrePressure,Timestamp\n",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project FRTyrePressure, Timestamp\n",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project RLTyrePressure, Timestamp\n",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project RRTyrePressure, Timestamp\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project FLTyreSurfaceTemp, Timestamp\n",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project FRTyreSurfaceTemp,Timestamp\n",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project RLTyreSurfaceTemp,Timestamp\n",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project RRTyreSurfaceTemp,Timestamp\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Wear",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project Timestamp, FLTyreWear ",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project Timestamp  , FRTyreWear",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project Timestamp  , RLTyreWear ",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project Timestamp  , RRTyreWear ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Damage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project Timestamp, FLTyreDamage ",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project Timestamp,FRTyreDamage ",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime \n| project Timestamp,RLTyreDamage ",
     "querySource": "raw"
    },
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\n| where $__timeFilter(Timestamp) and VehicleIndex == PlayerCarIndex \n| order by Timestamp , SessionTime  \n| project Timestamp,RRTyreDamage ",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Race", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Standings",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "database": "f1",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let participant = Participant\n| where $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 20\n| project Name, VehicleIndex;\nLap\n| where $__timeFilter(Timestamp)\n| order by Timestamp , SessionTime \n| take 20\n| join  kind=rightouter  participant on VehicleIndex\n| order by CarPosition asc\n| project CarPosition, Name, CurrentLapNum, GridPosition, CurrentLapTime, LastLapTime\n\n",
     "querySource": "raw"
    }
   ]
  }
 ]
}