{
 "title": "F1 ADX Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Packets Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| union CarStatus, Lap, Participant, Session\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime)\r\n| count\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Driver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Name",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Participant\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime \r\n| take 1\r\n| project Name",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Team",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Participant\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime | take 1\r\n| extend DriverTeamId = TeamId\r\n| join  kind=rightsemi Teams  on $left.DriverTeamId == $right.Id\r\n| project Name\r\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Nationality",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Participant\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime | take 1\r\n| join  kind=rightsemi Nationalities  on $left.Nationality == $right.Id\r\n| project Name\r\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Current Lap",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Lap\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project CurrentLapNum  ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Car Position",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Lap\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project CarPosition   ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Current Lap Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Lap\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project CurrentLapTime  ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Last Lap Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Lap\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project LastLapTime  ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Best Lap Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Lap\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project BestLapTime  ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Driver Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Lap\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project DriverStatus",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Lap Distance",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Lap\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project LapDistance  ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Total Distance",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Lap\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project TotalDistance  ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Time penalties",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Lap\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project TimePenalties   ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Pit Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Lap\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project PitStatus",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Grid Position",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Lap\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project GridPosition  ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Result Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Lap\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project ResultStatus",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Total Laps",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "\r\nSession\r\n| extend ingestionTime = ingestion_time() \r\n| where  $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime\r\n| take 1 \r\n| project TotalLaps ",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  {
   "title": "Session Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Session Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Session\r\n| extend ingestionTime = ingestion_time() \r\n| where  $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n| take 1 \r\n| project SessionTime",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Weather",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "\r\nSession\r\n| extend ingestionTime = ingestion_time() \r\n| where  $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime\r\n| take 1 \r\n| project Weather  ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Active Cars",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Participant\r\n| extend ingestionTime = ingestion_time() \r\n| where VehicleIndex == PlayerCarIndex and $__timeFilter(ingestionTime)\r\n| order by ingestionTime \r\n| take 1\r\n| project NumOfActiveCars ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Track",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Session\r\n| extend ingestionTime = ingestion_time() \r\n| where  $__timeFilter(ingestionTime)\r\n| order by ingestionTime, SessionTime | take 1\r\n| join  kind=rightsemi Tracks on $left.TrackId == $right.Id\r\n| project Name",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Session Duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "\r\nSession\r\n| extend ingestionTime = ingestion_time() \r\n| where  $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime\r\n| take 1 \r\n| project SessionDuration  ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "SessionTime Left",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "\r\nSession\r\n| extend ingestionTime = ingestion_time() \r\n| where  $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime\r\n| take 1 \r\n| project SessionTimeLeft ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Air Temp",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "\r\nSession\r\n| extend ingestionTime = ingestion_time() \r\n| where  $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n| take 1 \r\n| project AirTemp ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Track Temp",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "f12019",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "\r\nSession\r\n| extend ingestionTime = ingestion_time() \r\n| where  $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n| take 1 \r\n| project TrackTemp ",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  { "title": "Car", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time() \r\n| where VehicleIndex == PlayerCarIndex and $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n| take 1 \r\n| project Speed",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Engine",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time() \r\n| where VehicleIndex == PlayerCarIndex and $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n| take 1 \r\n| project EngineRPM ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where VehicleIndex == PlayerCarIndex and $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n|take 1\r\n| project Gear ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Anti lock brakes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "\r\nCarStatus\r\n| extend ingestionTime = ingestion_time()  \r\n| where  $__timeFilter(ingestionTime) and  VehicleIndex == PlayerCarIndex\r\n| order by ingestionTime , SessionTime\r\n| take 1 \r\n| project ABS  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Traction Control",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "\r\nCarStatus\r\n| extend ingestionTime = ingestion_time()  \r\n| where  $__timeFilter(ingestionTime) and  VehicleIndex == PlayerCarIndex\r\n| order by ingestionTime , SessionTime\r\n| take 1 \r\n| project TractionControl ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Fuel in Tank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "\r\nCarStatus\r\n| extend ingestionTime = ingestion_time()  \r\n| where  $__timeFilter(ingestionTime) and  VehicleIndex == PlayerCarIndex\r\n| order by ingestionTime , SessionTime\r\n| take 1 \r\n| project FuelInTank  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Fuel Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "\r\nCarStatus\r\n| extend ingestionTime = ingestion_time()  \r\n| where  $__timeFilter(ingestionTime) and  VehicleIndex == PlayerCarIndex\r\n| order by ingestionTime , SessionTime\r\n| take 1 \r\n| project FuelCapacity   ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Fuel Remaining Laps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "\r\nCarStatus\r\n| extend ingestionTime = ingestion_time()  \r\n| where  $__timeFilter(ingestionTime) and  VehicleIndex == PlayerCarIndex\r\n| order by ingestionTime , SessionTime\r\n| take 1 \r\n| project FuelRemainingLaps    ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "DRS Allowed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "\r\nCarStatus\r\n| extend ingestionTime = ingestion_time()  \r\n| where  $__timeFilter(ingestionTime) and  VehicleIndex == PlayerCarIndex\r\n| order by ingestionTime , SessionTime\r\n| take 1 \r\n| project DRSAllowed     ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "FIA Flags",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "\r\nCarStatus\r\n| extend ingestionTime = ingestion_time()  \r\n| where  $__timeFilter(ingestionTime) and  VehicleIndex == PlayerCarIndex\r\n| order by ingestionTime , SessionTime\r\n| take 1 \r\n| project VehicleFIAFlags       ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Damage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project EngineDamage , GearBoxDamage ,FLWingDamage , FRWingDamage , RearWingDamage  ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Gear & Clutch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "from": { "property": { "name": "CarTelemetry", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where VehicleIndex == PlayerCarIndex and $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n| project Gear , ingestionTime\r\n",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "from": { "property": { "name": "CarTelemetry", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where VehicleIndex == PlayerCarIndex and $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n| project Clutch  , ingestionTime\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Steering",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where VehicleIndex == PlayerCarIndex and $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n| project Steering , ingestionTime\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Throttle & Brake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "from": { "property": { "name": "CarTelemetry", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where VehicleIndex == PlayerCarIndex and $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n| project ingestionTime, Brake\r\n",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where VehicleIndex == PlayerCarIndex and $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n| project ingestionTime, Throttle \r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Engine RPM & Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where VehicleIndex == PlayerCarIndex and $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n| project EngineRPM , ingestionTime\r\n",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where VehicleIndex == PlayerCarIndex and $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n| project Speed   , ingestionTime\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Engine Temperature",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where VehicleIndex == PlayerCarIndex and $__timeFilter(ingestionTime)\r\n| order by ingestionTime , SessionTime \r\n| project EngineTemp  , ingestionTime\r\n",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Tyres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Tyre Compound",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project TyreVisualCompound\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tyre Wear",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 10, "x": 3, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project FLTyreWear, FRTyreWear, RLTyreWear , RRTyreWear ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tyre Damage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| take 1\r\n| project FLTyreDamage , FRTyreDamage , RLTyreDamage  , RRTyreDamage ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tyre Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime , SessionTime \r\n| project FLTyrePressure,ingestionTime\r\n",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime , SessionTime \r\n| project FRTyrePressure, ingestionTime\r\n",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime , SessionTime \r\n| project RLTyrePressure, ingestionTime\r\n",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime , SessionTime \r\n| project RRTyrePressure, ingestionTime\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tyre Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime , SessionTime \r\n| project FLTyreSurfaceTemp,ingestionTime\r\n",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime , SessionTime \r\n| project FRTyreSurfaceTemp,ingestionTime\r\n",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime , SessionTime \r\n| project RLTyreSurfaceTemp,ingestionTime\r\n",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarTelemetry\r\n| extend ingestionTime = ingestion_time()\r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime , SessionTime \r\n| project RRTyreSurfaceTemp,ingestionTime\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tyre Wear",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| project ingestionTime, FLTyreWear ",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| project ingestionTime  , FRTyreWear ",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| project ingestionTime  , RLTyreWear ",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| project ingestionTime  , RRTyreWear ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tyre Damage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| project ingestionTime, FLTyreDamage ",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| project ingestionTime,FRTyreDamage ",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| project ingestionTime,RLTyreDamage ",
     "querySource": "raw"
    },
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CarStatus\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime) and VehicleIndex == PlayerCarIndex \r\n| order by ingestionTime, SessionTime \r\n| project ingestionTime,RRTyreDamage ",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Race", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Standings",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "database": "f12019",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let participant = Participant\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime)\r\n| order by ingestionTime,SessionTime\r\n| take 20\r\n| project Name, VehicleIndex;\r\nLap\r\n| extend ingestionTime = ingestion_time() \r\n| where $__timeFilter(ingestionTime)\r\n| order by ingestionTime,SessionTime\r\n| take 20\r\n| join  kind=rightouter  participant on VehicleIndex\r\n| order by CarPosition asc\r\n| project CarPosition, Name, CurrentLapNum, GridPosition, CurrentLapTime, LastLapTime\r\n\r\n",
     "querySource": "raw"
    }
   ]
  }
 ]
}